version: '3'
services:
  web:
    build: backend
    ports:
      - "8000:3000"
    volumes:
      - ./backend:/home/battleship/backend
      - ./frontend:/home/battleship/frontend
    links:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"